src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

import java.util.LinkedHashMap;
import java.util.Map;

@Scope(value = WebApplicationContext.SCOPE_SESSION)
@Component
public class CarrinhoCompras {

    private Map<CarrinhoItem, Integer> itensCarrinho = new LinkedHashMap<>();

    public void add(CarrinhoItem item){
        itensCarrinho.put(item, getQuantidadeItem(item)+1);
    }

    public Integer getQuantidadeItem(CarrinhoItem item){
        if (!itensCarrinho.containsKey(item)){
            itensCarrinho.put(item, 0);
        }
        return itensCarrinho.get(item);
    }

    public int getQuantidade() {
        return itensCarrinho.values().stream().reduce(0, (proximo,acumulador) -> proximo + acumulador);
    }

    public Map<CarrinhoItem, Integer> getItensCarrinho() {
        return itensCarrinho;
    }

    public void setItensCarrinho(Map<CarrinhoItem, Integer> itensCarrinho) {
        this.itensCarrinho = itensCarrinho;
    }
}

src/main/java/br/com/casadocodigo/loja/models/Produto.java
package br.com.casadocodigo.loja.models;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.Calendar;
import java.util.List;
import java.util.Objects;

@Entity
public class Produto {

    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    private String nome;
    private String descricao;
    private int paginas;

//    @DateTimeFormat(pattern = "dd/MM/yyyy")
    private Calendar dataLancamento;

    private String sumarioPath;

    @ElementCollection
    private List<Preco> precos;

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public int getPaginas() {
        return paginas;
    }

    public void setPaginas(int paginas) {
        this.paginas = paginas;
    }

    @Override
    public String toString() {
        return "Produto{" +
                "nome='" + nome + '\'' +
                ", descricao='" + descricao + '\'' +
                ", paginas='" + paginas + '\'' +
                '}';
    }

    public int getId() {
        return id;
    }


    public List<Preco> getPrecos() {
        return precos;
    }

    public void setPrecos(List<Preco> precos) {
        this.precos = precos;
    }

    public Calendar getDataLancamento() {
        return dataLancamento;
    }

    public void setDataLancamento(Calendar dataLancamento) {
        this.dataLancamento = dataLancamento;
    }

    public String getSumarioPath() {
        return sumarioPath;
    }

    public void setSumarioPath(String sumarioPath) {
        this.sumarioPath = sumarioPath;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Produto produto = (Produto) o;
        return getId() == produto.getId();
    }

    @Override
    public int hashCode() {

        return Objects.hash(getId());
    }
}

src/main/java/br/com/casadocodigo/loja/controllers/ProdutosController.java
package br.com.casadocodigo.loja.controllers;

import br.com.casadocodigo.loja.daos.ProdutoDAO;
import br.com.casadocodigo.loja.infra.FileSaver;
import br.com.casadocodigo.loja.models.Produto;
import br.com.casadocodigo.loja.models.TipoPreco;
import br.com.casadocodigo.loja.utils.Strings;
import br.com.casadocodigo.loja.validations.ProdutoValidation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import org.apache.log4j.Logger;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.validation.Valid;
import java.util.List;

@Controller
@RequestMapping(value = "/produtos")
public class ProdutosController {

    @Autowired
    ProdutoDAO produtoDAO;

    @Autowired
    FileSaver fileSaver;

    private static final Logger logger = Logger.getLogger(ProdutosController.class);

    @InitBinder
    public void initBinder(WebDataBinder dataBinder){
        dataBinder.addValidators(new ProdutoValidation());
    }

    @RequestMapping(value = "/form")
    public ModelAndView form(Produto produto){
        logger.info("Acessando formulário de produtos");
        ModelAndView modelAndView = new ModelAndView("produtos/form");
        modelAndView.addObject("tipos", TipoPreco.values());
        return modelAndView;
    }

    @RequestMapping(method = RequestMethod.POST)
    public ModelAndView gravar(MultipartFile sumario, @Valid Produto produto, BindingResult bindingResult, RedirectAttributes redirectAttributes){

        if (bindingResult.hasErrors()){
            logger.warn("ERRO DE VALIDAÇÃO DE PRODUTOS");
            return form(produto);
        }

        System.out.println(sumario.getOriginalFilename());

        produto.setSumarioPath(fileSaver.write("arquivos-sumario", sumario));
        System.out.println(produto);
        produtoDAO.gravar(produto);
        redirectAttributes.addFlashAttribute(Strings.ATRIBUTO_MENSAGEM_SUCESSO, "Produto cadastrado com sucesso");
//        tem que redicionar pra matar a requisição de post, senão bug do F5
        return new ModelAndView("redirect:/produtos");
    }

    @RequestMapping(method = RequestMethod.GET)
    public ModelAndView listar(){
        ModelAndView modelAndView = new ModelAndView("produtos/lista");
        List<Produto> produtos = produtoDAO.listar();
        modelAndView.addObject("produtos", produtos);
        return modelAndView;
    }

    @RequestMapping(method = RequestMethod.GET, value = "/detalhe/{id}")
    public ModelAndView detalhe(@PathVariable("id") int id){
        ModelAndView modelAndView = new ModelAndView("produtos/detalhe");
        Produto produto = produtoDAO.findById(id);
        modelAndView.addObject("produto", produto);
        return modelAndView;
    }

}

src/main/webapp/WEB-INF/views/produtos/detalhe.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<!DOCTYPE html>
<html>
<head>
	<c:url value="/" var="contextPath" />
	  <meta charset="utf-8"/>
		  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
		  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
		<link rel="icon"
			href="//cdn.shopify.com/s/files/1/0155/7645/t/177/assets/favicon.ico?11981592617154272979"
			type="image/ico" />
		<link href="https://plus.googlecom/108540024862647200608"
			rel="publisher"/>
		<title>Livros de Java, SOA, Android, iPhone, Ruby on Rails e
			muito mais - Casa do Código</title>
		<link href="${contextPath}resources/css/cssbase-min.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700'
			rel='stylesheet'/>
		<link href="${contextPath}resources/css/fonts.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/fontello-ie7.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/fontello-embedded.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/fontello.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/style.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/layout-colors.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/responsive-style.css"
			rel="stylesheet" type="text/css" media="all" />
		<link href="${contextPath}resources/css/guia-do-programador-style.css"
			rel="stylesheet" type="text/css"  media="all"  />
	    <link href="${contextPath}resources/css/produtos.css"
	    	rel="stylesheet" type="text/css"  media="all"  />
		<link rel="canonical" href="http://www.casadocodigo.com.br/" />	
</head>
<body>

  <header id="layout-header">
		<div class="clearfix container">
			<a href="/" id="logo">
			</a>
			<div id="header-content">
				<nav id="main-nav">
					
					<ul class="clearfix">
						<li><a href="/cart" rel="nofollow">Carrinho (${carrinhoCompras.quantidade})</a></li>

						<li><a href="/pages/sobre-a-casa-do-codigo" rel="nofollow">Sobre Nós</a></li>

						<li><a href="/pages/perguntas-frequentes" rel="nofollow">Perguntas Frequentes</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<nav class="categories-nav">
		<ul class="container">
			<li class="category"><a href="http://www.casadocodigo.com.br">Home</a></li>
			<li class="category"><a href="/collections/livros-de-agile">
					Agile </a></li>
			<li class="category"><a href="/collections/livros-de-front-end">
					Front End </a></li>
			<li class="category"><a href="/collections/livros-de-games">
					Games </a></li>
			<li class="category"><a href="/collections/livros-de-java">
					Java </a></li>
			<li class="category"><a href="/collections/livros-de-mobile">
					Mobile </a></li>
			<li class="category"><a
				href="/collections/livros-desenvolvimento-web"> Web </a></li>
			<li class="category"><a href="/collections/outros"> Outros </a></li>
		</ul>
	</nav>

	<article id="livro-css-eficiente">
		  <header id="product-highlight" class="clearfix">
		    <div id="product-overview" class="container">
		      <img width="280px" height="395px" src="http://cdn.shopify.com/s/files/1/0155/7645/products/css-eficiente-featured_large.png?v=1435245145" class="product-featured-image" />
		      <h1 class="product-title">${produto.nome}</h1>
		      <p class="product-author">
		        <span class="product-author-link">
		          
		        </span>
		      </p>	
			
		    <p class="book-description">
		    	${produto.descricao}
		    </p>
		    </div>
		  </header>
	
	  
	  <section class="buy-options clearfix">  
	  <form action="<c:url value="/carrinho/add"/>" method="post" class="container">
	    <ul id="variants" class="clearfix">
			<c:forEach items="${produto.precos}" var="preco" varStatus="status">
	    	  <li class="buy-option">
                <input type="hidden" name="produtoId" value="${produto.id}">
                <input type="radio" name="tipoPreco" class="variant-radio" id="product-variant-9720393823" value="${preco.tipoPreco}"  checked="checked"  />
	            <label  class="variant-label" for="product-variant-9720393823">
	              ${preco.tipoPreco}
	            </label>
	            <small class="compare-at-price">R$ ${preco.valor * 1.5}</small>
	            <p class="variant-price">R$ ${preco.valor}</p>
	          </li>
			</c:forEach>
	    </ul>
	    <button type="submit" class="submit-image icon-basket-alt" alt="Compre Agora" title="Compre Agora"></button>
	    
	  </form>
	  
	</section>
	  
	<div class="container">
	  <section class="summary">
	    <ul>
	      	<li><h3>E muito mais... <a href='/pages/sumario-java8'>veja o sumário</a>.</h3></li>
	    </ul>
	  </section>
	  
	  <section class="data product-detail">
	    <h2 class="section-title">Dados do livro:</h2>
	    <p>Número de páginas: <span>${produto.paginas}</span></p>
	    <p></p>
		  <p>Data de publicação: <fmt:formatDate value="${produto.dataLancamento.time}" pattern="dd/MM/yyyy"/> </p>
	    <p>Encontrou um erro? <a href='/submissao-errata' target='_blank'>Submeta uma errata</a></p>
	  </section>
	</div>
	
	</article>	

	<footer id="layout-footer">
		<div class="clearfix container">
			<div id="collections-footer">
				<!-- cdc-footer -->
				<p class="footer-title">Coleções de Programação</p>
				<ul class="footer-text-links">
					<li><a href="/collections/livros-de-java">Java</a></li>
					<li><a href="/collections/livros-desenvolvimento-web">Desenvolvimento
							Web</a></li>
					<li><a href="/collections/livros-de-mobile">Mobile</a></li>
					<li><a href="/collections/games">Games</a></li>
					<li><a href="/collections/livros-de-front-end">Front End</a></li>
				</ul>
				<p class="footer-title">Outros Assuntos</p>
				<ul class="footer-text-links">
					<li><a href="/collections/livros-de-agile">Agile</a></li>
					<li><a href="/collections/outros">e outros...</a></li>
				</ul>
			</div>
			<div id="social-footer">
				<!-- books-footer -->
				<p class="footer-title">Links da Casa do Código</p>
				<ul class="footer-text-links">
					<li><a href="http://livros.casadocodigo.com.br" rel="nofollow">Meus
							E-books</a></li>
					<li><a href="/pages/sobre-a-casa-do-codigo">Sobre a Casa
							do Código</a></li>
					<li><a href="/pages/perguntas-frequentes">Perguntas
							Frequentes</a></li>
					<li><a href="https://www.caelum.com.br">Caelum - Ensino e
							Inovação</a></li>
					<li><a href="http://www.codecrushing.com/" rel="nofollow">Code
							Crushing</a></li>
					<li><a
						href="http://www.casadocodigo.com.br/pages/politica-de-privacidade"
						rel="nofollow">Política de Privacidade</a></li>
				</ul>
				<p class="footer-title">Redes Sociais</p>
				<ul>
					<li class="social-links"><a
						href="http://www.twitter.com/casadocodigo" target="_blank"
						id="twitter" rel="nofollow">Facebook</a> <a
						href="http://www.facebook.com/casadocodigo" target="_blank"
						id="facebook" rel="nofollow">Twitter</a></li>
				</ul>
			</div>
			<div id="newsletter-footer">
				<!-- social-footer -->
				<p class="footer-title">Receba as Novidades e Lançamentos</p>
				<div id="form-newsletter">
					<form
						action=""
						method="POST" id="ss-form" class="form-newsletter">
						<ul>
							<li><input type="hidden" name="pageNumber" value="0"/><input
								type="hidden" name="backupCache" value=""/><input
								type="email" name="entry.0.single" value="" class="ss-q-short"
								id="entry_0" placeholder="seu@email.com"/></li>
							<li><input type="submit" name="submit"
								value="Quero Receber!" id="submit-newsletter"/></li>
						</ul>
					</form>
					<ul>
						<li class="ie8"><a
							href=""
							rel="nofollow">Receba as Novidades e Lançamentos</a></li>
					</ul>
				</div>
				<ul class="footer-payments">
					<li></li>
					<li></li>
				</ul>
			</div>
		</div>
	</footer>
</body>
</html>

src/main/webapp/WEB-INF/views/produtos/form.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<html>
<head>
    <title>Formulário de cadastro de livro</title>
</head>
<body>
    <%--<form style="width: 50%" action="/casadocodigo/produtos" method="post">--%>
    <%--ALTERNATIVE modelAttribute="produto"--%>
    <form:form action="${s:mvcUrl('PC#gravar').build()}" method="post" enctype="multipart/form-data" commandName="produto">
        <div style="height: 50px; margin: 10px;">
            <label>Nome</label>
            <form:input path="nome"/>
            <form:errors path="nome"/>
        </div>
        <div style="height: 50px; margin: 10px;">
            <label>Descrição</label>
            <form:textarea path="descricao"/>
            <form:errors path="descricao"/>
        </div>
        <div style="height: 50px; margin: 10px;">
            <label>Nº Páginas</label>
            <form:input path="paginas"/>
            <form:errors path="paginas"/>
        </div>
        <div style="height: 50px; margin: 10px;">
            <label>Data lançamento</label>
            <form:input path="dataLancamento"/>
            <form:errors path="dataLancamento"/>
        </div>
        <c:forEach items="${tipos}" var="tipoPreco" varStatus="status">
            <div style="height: 50px; margin: 10px;">
                <label>${tipoPreco}</label>
                <form:input path="precos[${status.index}].valor"/>
                <form:input type="hidden" path="precos[${status.index}].tipoPreco" value="${tipoPreco}"/>
            </div>
        </c:forEach>
        <div>
            <label>Sumário</label>
            <input type="file" name="sumario"/>
        </div>
        <button style="width: 100%" type="submit">Cadastrar</button>
    <%--</form>--%>
    </form:form>
</body>
</html>

src/main/webapp/WEB-INF/views/produtos/lista.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<html>
<head>
    <title>Formulário de cadastro de livro</title>
</head>
<body>
    <h1>Lista de produtos:</h1>

    <h2 style="background-color: #24cd2d">${mensagem_sucesso}</h2>

       <table style="border: black solid 1px; width: 100%">
        <thead>
            <tr>
                <td>Título</td>
                <td>Descrição</td>
                <td>Data lançamento</td>
                <td>Páginas</td>
            </tr>
        </thead>
        <tbody>
            <c:forEach items="${produtos}" var="produto" varStatus="status">
                <tr>
                    <td><a href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build()}"> ${produto.nome}</a></td>
                    <td>${produto.descricao}</td>
                    <td><fmt:formatDate value="${produto.dataLancamento.time}" pattern="dd/MM/yyyy"/> </td>
                    <td>${produto.paginas}</td>
                </tr>
            </c:forEach>
        </tbody>
    </table>
</body>
</html>

src/main/webapp/WEB-INF/views/produtos/ok.jsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 04/01/18
  Time: 16:37
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Sucesso</title>
</head>
<body>
    <h1>Livro cadastrado com sucesso</h1>
</body>
</html>